version: '3'

services:
  # app:
  #   build: .
  #   container_name: app
  #   command: .docker/start.sh
  #   volumes:
  #     - .:/home/node/app
  #   ports:
  #     - 3000:3000

  db:
    image: neo4j:4.4-enterprise
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment: 
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.memory.heap.initial_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
      - bridge
    # healthcheck:
    #   test: wget http://localhost:7474 || exit 1
    #   interval: 1s
    #   timeout: 10s
    #   retries: 20
    #   start_period: 40s

networks:
  bridge:
    # external: true
      