MATCH (n) return count(n);

// CREATE CONSTRAINT ON (n:Movie) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Language) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Country) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Genre) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:ProductionCompany) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Collection) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Person) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:User) ASSERT n.id IS UNIQUE;
// CREATE CONSTRAINT ON (n:Keyword) ASSERT n.id IS UNIQUE;
